### ISSUE TITLE
Update Crux build to use Theo based yaml design tokens instead of jsonToScss

### ISSUE THREAD

**Issue by joekarasek** [basaltinc/crux#2]

**Comment by EvanLovely** [comment]
This is not finished; the Theo tokens are imported into Sass, but the final CSS is not different if you change the Theo tokens - it's still using the original Sass vars.

**Comment by joekarasek** [comment]
Pushing this one back to "needs more info" due to 1) ongoing changes to crux and 2) need to address ticket #196.

**Comment by joekarasek** [comment]
This ticket is no longer relevant as Basalt.io is undergoing a brand refresh. Design token pipeline decision belongs to that project.
